version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
    ports:
      - "4566:4566"  # Localstack main endpoint
      - "4572:4572"  # S3 service endpoint
    volumes:
      - "./localstack-data:/var/lib/localstack"  # Store state locally
